server:
  port: 8080
spring:
  application:
    name: 'api-gateway'
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
      routes:
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/home/**
